url: "https://michael.kafarowski.com"
baseurl: "/"

layout: default
title: "Michael Kafarowski"
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
permalink: /blog/:year/:month/:day/:title/
collections:
  projects:
    output: true