url: "https://michael.kafarowski.com"
baseurl: "/"

layout: default
title: "Michael Kafarowski"
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
permalink: /blog/:year/:month/:day/:title/
collections:
  projects:
    output: true

kramdown:
  toc_levels: 2..6